/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Injectable, NgZone, inject } from '@angular/core';

/**
 * Service to handle code block copy functionality.
 * Attaches a global click handler for copy buttons generated by the markdown pipe.
 */
@Injectable({
  providedIn: 'root',
})
export class CodeCopyService {
  private readonly ngZone = inject(NgZone);
  private initialized = false;

  /**
   * Initialize the global click handler for copy buttons.
   * Should be called once from the app component.
   */
  initialize(): void {
    if (this.initialized) return;
    this.initialized = true;

    // Run outside Angular zone for better performance
    this.ngZone.runOutsideAngular(() => {
      document.addEventListener('click', (event: MouseEvent) => {
        const target = event.target as HTMLElement;
        const copyButton = target.closest('.copy-button') as HTMLElement | null;

        if (copyButton) {
          this.handleCopyClick(copyButton);
        }
      });
    });
  }

  /**
   * Handle copy button click.
   */
  private async handleCopyClick(button: HTMLElement): Promise<void> {
    const code = button.dataset['code'];
    if (!code) return;

    // Decode HTML entities
    const decodedCode = this.decodeHtmlEntities(code);

    try {
      await navigator.clipboard.writeText(decodedCode);
      this.showCopiedFeedback(button);
    } catch (err) {
      // Fallback for older browsers
      this.fallbackCopy(decodedCode);
      this.showCopiedFeedback(button);
    }
  }

  /**
   * Decode HTML entities from the data attribute.
   */
  private decodeHtmlEntities(text: string): string {
    return text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#039;/g, "'")
      .replace(/&#10;/g, '\n');
  }

  /**
   * Show visual feedback when code is copied.
   */
  private showCopiedFeedback(button: HTMLElement): void {
    button.classList.add('copied');

    // Update button text
    const textSpan = button.querySelector('.copy-text');
    const originalText = textSpan?.textContent;
    if (textSpan) {
      textSpan.textContent = 'Copied!';
    }

    // Update icon to checkmark
    const svg = button.querySelector('svg');
    if (svg) {
      svg.innerHTML = `
        <path d="M20 6L9 17l-5-5"></path>
      `;
    }

    // Reset after 2 seconds
    setTimeout(() => {
      button.classList.remove('copied');
      if (textSpan) {
        textSpan.textContent = originalText || 'Copy';
      }
      if (svg) {
        svg.innerHTML = `
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
        `;
      }
    }, 2000);
  }

  /**
   * Fallback copy method for older browsers.
   */
  private fallbackCopy(text: string): void {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    document.execCommand('copy');
    textArea.remove();
  }
}
