/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Injectable, inject, NgZone } from '@angular/core';

/**
 * Service to handle code block and table copy functionality.
 * Attaches a global click handler for copy buttons generated by the markdown pipe.
 */
@Injectable({
  providedIn: 'root',
})
export class CodeCopyService {
  private readonly ngZone = inject(NgZone);
  private initialized = false;

  /**
   * Initialize the global click handler for copy buttons.
   * Should be called once from the app component.
   */
  initialize(): void {
    if (this.initialized) return;
    this.initialized = true;

    // Run outside Angular zone for better performance
    this.ngZone.runOutsideAngular(() => {
      document.addEventListener('click', (event: MouseEvent) => {
        const target = event.target as HTMLElement;

        // Handle code block copy
        const copyButton = target.closest('.copy-button') as HTMLElement | null;
        if (copyButton) {
          this.handleCopyClick(copyButton);
          return;
        }

        // Handle table copy
        const tableButton = target.closest('.copy-table-button') as HTMLElement | null;
        if (tableButton) {
          this.handleTableCopyClick(tableButton);
        }
      });
    });
  }

  /**
   * Handle code copy button click.
   */
  private async handleCopyClick(button: HTMLElement): Promise<void> {
    const code = button.dataset['code'];
    if (!code) return;

    // Decode HTML entities
    const decodedCode = this.decodeHtmlEntities(code);

    try {
      await navigator.clipboard.writeText(decodedCode);
      this.showCopiedFeedback(button, 'code');
    } catch {
      // Fallback for older browsers
      this.fallbackCopy(decodedCode);
      this.showCopiedFeedback(button, 'code');
    }
  }

  /**
   * Handle table copy button click.
   * Extracts table data as TSV (tab-separated values) for Google Sheets compatibility.
   */
  private async handleTableCopyClick(button: HTMLElement): Promise<void> {
    const tableId = button.dataset['tableId'];
    if (!tableId) return;

    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;

    // Extract table data as TSV
    const tsv = this.extractTableAsTSV(table);

    try {
      await navigator.clipboard.writeText(tsv);
      this.showCopiedFeedback(button, 'table');
    } catch {
      this.fallbackCopy(tsv);
      this.showCopiedFeedback(button, 'table');
    }
  }

  /**
   * Extract table data as TSV (tab-separated values).
   * This format is compatible with Google Sheets, Excel, and other spreadsheet apps.
   */
  private extractTableAsTSV(table: HTMLTableElement): string {
    const rows: string[] = [];

    // Process all rows (thead and tbody)
    const allRows = table.querySelectorAll('tr');
    allRows.forEach((row: HTMLTableRowElement) => {
      const cells: string[] = [];
      const cellElements = row.querySelectorAll('th, td');
      cellElements.forEach((cell: Element) => {
        // Get text content, escape tabs and newlines
        let text = (cell.textContent || '').trim();
        // Escape quotes and wrap in quotes if contains special characters
        if (text.includes('\t') || text.includes('\n') || text.includes('"')) {
          text = `"${text.replace(/"/g, '""')}"`;
        }
        cells.push(text);
      });
      rows.push(cells.join('\t'));
    });

    return rows.join('\n');
  }

  /**
   * Decode HTML entities from the data attribute.
   */
  private decodeHtmlEntities(text: string): string {
    return text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#039;/g, "'")
      .replace(/&#10;/g, '\n');
  }

  /**
   * Show visual feedback when content is copied.
   */
  private showCopiedFeedback(button: HTMLElement, _type: 'code' | 'table'): void {
    button.classList.add('copied');

    // Update button text
    const textSpan = button.querySelector('.copy-text');
    const originalText = textSpan?.textContent;
    if (textSpan) {
      textSpan.textContent = 'Copied!';
    }

    // Update icon to checkmark
    const svg = button.querySelector('svg');
    const originalSvgContent = svg?.innerHTML;
    if (svg) {
      svg.innerHTML = `
        <path d="M20 6L9 17l-5-5"></path>
      `;
    }

    // Reset after 2 seconds
    setTimeout(() => {
      button.classList.remove('copied');
      if (textSpan) {
        textSpan.textContent = originalText || 'Copy';
      }
      if (svg && originalSvgContent) {
        svg.innerHTML = originalSvgContent;
      }
    }, 2000);
  }

  /**
   * Fallback copy method for older browsers.
   */
  private fallbackCopy(text: string): void {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    document.execCommand('copy');
    textArea.remove();
  }
}
