// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file was generated by jsonschemagen. DO NOT EDIT.

package exp

import (
	"github.com/firebase/genkit/go/ai"
)

// Artifact represents a named collection of parts produced during a session.
// Examples: generated files, images, code snippets, diagrams, etc.
type Artifact struct {
	// Metadata contains additional artifact-specific data.
	Metadata map[string]any `json:"metadata,omitempty"`
	// Name identifies the artifact (e.g., "generated_code.go", "diagram.png").
	Name string `json:"name,omitempty"`
	// Parts contains the artifact content (text, media, etc.).
	Parts []*ai.Part `json:"parts"`
}

// SessionFlowInit is the input for starting an session flow invocation.
// Provide either SnapshotID (to load from store) or State (direct state).
type SessionFlowInit[State any] struct {
	// SnapshotID loads state from a persisted snapshot.
	// Mutually exclusive with State.
	SnapshotID string `json:"snapshotId,omitempty"`
	// State provides direct state for the invocation.
	// Mutually exclusive with SnapshotID.
	State *SessionState[State] `json:"state,omitempty"`
}

// SessionFlowInput is the input sent to an session flow during a conversation turn.
type SessionFlowInput struct {
	// Messages contains the user's input for this turn.
	Messages []*ai.Message `json:"messages,omitempty"`
	// ToolRestarts contains tool request parts to re-execute interrupted tools.
	// Use [ai.ToolDef.RestartWith] to create these parts from an interrupted
	// tool request. When set, the generate call resumes with these restarts
	// instead of treating Messages as tool responses.
	ToolRestarts []*ai.Part `json:"toolRestarts,omitempty"`
}

// SessionFlowOutput is the output when an session flow invocation completes.
// It wraps SessionFlowResult with framework-managed fields.
type SessionFlowOutput[State any] struct {
	// Artifacts contains artifacts produced during the session.
	Artifacts []*Artifact `json:"artifacts,omitempty"`
	// Message is the last model response message from the conversation.
	Message *ai.Message `json:"message,omitempty"`
	// SnapshotID is the ID of the snapshot created at the end of this invocation.
	// Empty if no snapshot was created (callback returned false or no store configured).
	SnapshotID string `json:"snapshotId,omitempty"`
	// State contains the final conversation state.
	// Only populated when state is client-managed (no store configured).
	State *SessionState[State] `json:"state,omitempty"`
}

// SessionFlowResult is the return value from an SessionFlowFunc.
// It contains the user-specified outputs of the agent invocation.
type SessionFlowResult struct {
	// Artifacts contains artifacts produced during the session.
	Artifacts []*Artifact `json:"artifacts,omitempty"`
	// Message is the last model response message from the conversation.
	Message *ai.Message `json:"message,omitempty"`
}

// SessionFlowStreamChunk represents a single item in the session flow's output stream.
// Multiple fields can be populated in a single chunk.
type SessionFlowStreamChunk[Stream any] struct {
	// Artifact contains a newly produced artifact.
	Artifact *Artifact `json:"artifact,omitempty"`
	// ModelChunk contains generation tokens from the model.
	ModelChunk *ai.ModelResponseChunk `json:"modelChunk,omitempty"`
	// Status contains user-defined structured status information.
	// The Stream type parameter defines the shape of this data.
	Status Stream `json:"status,omitempty"`
	// TurnEnd is non-nil when the session flow has finished processing the current
	// input. It groups all turn-end signals (snapshot ID, etc.) so callers can
	// check a single field. When set, the client should stop iterating and may
	// send the next input.
	TurnEnd *TurnEnd `json:"turnEnd,omitempty"`
}

// SessionState is the portable conversation state that flows between client
// and server. It contains only the data needed for conversation continuity.
type SessionState[State any] struct {
	// Artifacts are named collections of parts produced during the conversation.
	Artifacts []*Artifact `json:"artifacts,omitempty"`
	// Custom is the user-defined state associated with this conversation.
	Custom State `json:"custom,omitempty"`
	// InputVariables is the input used for session flows that require input variables
	// (e.g. prompt-backed session flows).
	InputVariables any `json:"inputVariables,omitempty"`
	// Messages is the conversation history (user/model exchanges).
	// Does NOT include prompt-rendered messages — those are rendered fresh each turn.
	Messages []*ai.Message `json:"messages,omitempty"`
}

// SnapshotEvent identifies what triggered a snapshot.
type SnapshotEvent string

const (
	// TurnEnd indicates the snapshot was triggered at the end of a turn.
	SnapshotEventTurnEnd SnapshotEvent = "turnEnd"
	// InvocationEnd indicates the snapshot was triggered at the end of the invocation.
	SnapshotEventInvocationEnd SnapshotEvent = "invocationEnd"
)

// TurnEnd groups the signals emitted when a session flow turn finishes.
// A TurnEnd value is emitted exactly once per turn, regardless of whether a
// snapshot was persisted.
type TurnEnd struct {
	// SnapshotID is the ID of the snapshot persisted at the end of this turn.
	// Empty if no snapshot was created (callback returned false or no store
	// configured).
	SnapshotID string `json:"snapshotId,omitempty"`
}
