# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Pydantic schemas for AI-generated release intelligence.

These models define the structured output schemas that Genkit's
``ai.generate()`` uses to produce typed, parseable JSON from any
model provider. The schemas serve double duty:

1. **Generation constraint** — passed to ``Output(schema=ReleaseSummary)``
   so the model is forced to produce valid JSON matching the schema.
2. **Application type** — ``response.output`` returns a validated
   ``ReleaseSummary`` instance, not a raw dict.

Usage::

    from genkit.ai import Output
    from releasekit.schemas_ai import ReleaseSummary

    response = await ai.generate(
        model='ollama/gemma3:4b',
        prompt=prompt,
        output=Output(schema=ReleaseSummary),
    )
    summary: ReleaseSummary = response.output
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ReleaseStats(BaseModel):
    """Quantitative release statistics.

    Provides hard numbers for the release summary header. All fields
    are non-negative integers with sensible defaults so the model can
    omit fields it cannot determine from the changelog alone.
    """

    commit_count: int = Field(
        default=0,
        ge=0,
        description='Total number of commits in this release.',
    )
    packages_changed: int = Field(
        default=0,
        ge=0,
        description='Number of packages with changes.',
    )
    files_changed: int = Field(
        default=0,
        ge=0,
        description='Approximate number of files changed.',
    )
    days_since_last_release: int = Field(
        default=0,
        ge=0,
        description='Days elapsed since the previous release.',
    )


class ReleaseSummary(BaseModel):
    """Structured release summary generated by AI.

    This is the primary output schema for Phase 10 (AI-Powered Release
    Notes). Each field maps to a section of the generated release notes.
    The model fills in what it can determine from the raw changelog;
    fields default to empty so partial output is always valid.
    """

    overview: str = Field(
        default='',
        description=(
            'A 2-3 sentence high-level overview of the release. Mention the most important theme or headline change.'
        ),
    )
    highlights: list[str] = Field(
        default_factory=list,
        description=('Top 5-10 user-facing highlights. Each item is a single sentence describing a notable change.'),
    )
    breaking_changes: list[str] = Field(
        default_factory=list,
        description=(
            'Breaking changes with brief migration notes. Each item describes what changed and what users need to do.'
        ),
    )
    new_plugins: list[str] = Field(
        default_factory=list,
        description='Names of new plugins or packages added in this release.',
    )
    deprecations: list[str] = Field(
        default_factory=list,
        description='Features or APIs deprecated in this release.',
    )
    security_fixes: list[str] = Field(
        default_factory=list,
        description='Security-related fixes included in this release.',
    )
    package_summaries: dict[str, str] = Field(
        default_factory=dict,
        description=(
            'Per-package one-line summary. Keys are package names, values are single-sentence descriptions of changes.'
        ),
    )
    contributors: list[str] = Field(
        default_factory=list,
        description='GitHub handles of contributors (from commit metadata).',
    )
    stats: ReleaseStats = Field(
        default_factory=ReleaseStats,
        description='Quantitative release statistics.',
    )


class ReleaseCodename(BaseModel):
    """AI-generated release codename following a configurable theme.

    Themes follow the pattern of well-known projects:
    - ``"mountains"`` — Alpine peaks (like Android releases)
    - ``"animals"`` — Alliterative animal names (like Ubuntu)
    - ``"space"`` — Celestial bodies and missions
    - ``"mythology"`` — Gods, heroes, and legends
    - ``"gems"`` — Precious stones and minerals
    - ``"weather"`` — Meteorological phenomena
    - ``"cities"`` — World cities
    - Or any custom theme string the user provides.

    The codename should be memorable, fun, and loosely reflect the
    release's character (e.g. a big release gets a grander name).
    """

    codename: str = Field(
        default='',
        description=('The release codename. A single memorable word or short phrase following the configured theme.'),
    )
    theme: str = Field(
        default='',
        description='The theme used to generate this codename.',
    )
    tagline: str = Field(
        default='',
        description=(
            'A one-sentence tagline connecting the codename to the '
            'release highlights (e.g. "Denali — towering performance '
            'improvements across all providers").'
        ),
    )
