// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was generated by jsonschemagen. DO NOT EDIT.

package genkit

type Candidate struct {
	Custom        any              `json:"custom,omitempty"`
	FinishMessage string           `json:"finishMessage,omitempty"`
	FinishReason  FinishReason     `json:"finishReason,omitempty"`
	Index         int              `json:"index,omitempty"`
	Message       *Message         `json:"message,omitempty"`
	Usage         *GenerationUsage `json:"usage,omitempty"`
}

type FinishReason string

const (
	FinishReasonStop    FinishReason = "stop"
	FinishReasonLength  FinishReason = "length"
	FinishReasonBlocked FinishReason = "blocked"
	FinishReasonOther   FinishReason = "other"
	FinishReasonUnknown FinishReason = "unknown"
)

type DocumentData struct {
	Content  []any          `json:"content,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

type FlowError struct {
	Error      string `json:"error,omitempty"`
	Stacktrace string `json:"stacktrace,omitempty"`
}

type FlowInvokeEnvelopeMessage struct {
	Resume       *FlowInvokeEnvelopeMessage_resume       `json:"resume,omitempty"`
	Retry        *FlowInvokeEnvelopeMessage_retry        `json:"retry,omitempty"`
	RunScheduled *FlowInvokeEnvelopeMessage_runScheduled `json:"runScheduled,omitempty"`
	Schedule     *FlowInvokeEnvelopeMessage_schedule     `json:"schedule,omitempty"`
	Start        *FlowInvokeEnvelopeMessage_start        `json:"start,omitempty"`
	State        *FlowInvokeEnvelopeMessage_state        `json:"state,omitempty"`
}

type FlowInvokeEnvelopeMessage_resume struct {
	FlowID  string `json:"flowId,omitempty"`
	Payload any    `json:"payload,omitempty"`
}

type FlowInvokeEnvelopeMessage_retry struct {
	FlowID string `json:"flowId,omitempty"`
}

type FlowInvokeEnvelopeMessage_runScheduled struct {
	FlowID string `json:"flowId,omitempty"`
}

type FlowInvokeEnvelopeMessage_schedule struct {
	Delay float64 `json:"delay,omitempty"`
	Input any     `json:"input,omitempty"`
}

type FlowInvokeEnvelopeMessage_start struct {
	Input  any               `json:"input,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
}

type FlowInvokeEnvelopeMessage_state struct {
	FlowID string `json:"flowId,omitempty"`
}

type FlowResponse struct {
	Response any `json:"response,omitempty"`
}

type FlowState struct {
	BlockedOnStep   any                   `json:"blockedOnStep,omitempty"`
	Cache           map[string]any        `json:"cache,omitempty"`
	EventsTriggered map[string]any        `json:"eventsTriggered,omitempty"`
	Executions      []*FlowStateExecution `json:"executions,omitempty"`
	FlowID          string                `json:"flowId,omitempty"`
	Input           any                   `json:"input,omitempty"`
	Name            string                `json:"name,omitempty"`
	Operation       *Operation            `json:"operation,omitempty"`
	// start time in milliseconds since the epoch
	StartTime    Milliseconds `json:"startTime,omitempty"`
	TraceContext string       `json:"traceContext,omitempty"`
}

type FlowStateExecution struct {
	// end time in milliseconds since the epoch
	EndTime Milliseconds `json:"endTime,omitempty"`
	// start time in milliseconds since the epoch
	StartTime Milliseconds `json:"startTime,omitempty"`
	TraceIDs  []string     `json:"traceIds,omitempty"`
}

type GenerationConfig struct {
	Custom          map[string]any `json:"custom,omitempty"`
	MaxOutputTokens float64        `json:"maxOutputTokens,omitempty"`
	StopSequences   []string       `json:"stopSequences,omitempty"`
	Temperature     float64        `json:"temperature,omitempty"`
	TopK            float64        `json:"topK,omitempty"`
	TopP            float64        `json:"topP,omitempty"`
}

type GenerationRequest struct {
	Candidates float64                  `json:"candidates,omitempty"`
	Config     *GenerationConfig        `json:"config,omitempty"`
	Messages   []*Message               `json:"messages,omitempty"`
	Output     *GenerationRequestOutput `json:"output,omitempty"`
	Tools      []*ToolDefinition        `json:"tools,omitempty"`
}

type GenerationRequestOutput struct {
	Format OutputFormat   `json:"format,omitempty"`
	Schema map[string]any `json:"schema,omitempty"`
}

type OutputFormat string

const (
	OutputFormatJSON OutputFormat = "json"
	OutputFormatText OutputFormat = "text"
)

type GenerationResponse struct {
	Candidates []*Candidate     `json:"candidates,omitempty"`
	Custom     any              `json:"custom,omitempty"`
	Usage      *GenerationUsage `json:"usage,omitempty"`
}

type GenerationUsage struct {
	Custom       map[string]float64 `json:"custom,omitempty"`
	InputTokens  float64            `json:"inputTokens,omitempty"`
	OutputTokens float64            `json:"outputTokens,omitempty"`
	TotalTokens  float64            `json:"totalTokens,omitempty"`
}

type Message struct {
	Content []*Part `json:"content,omitempty"`
	Role    Role    `json:"role,omitempty"`
}

type Operation struct {
	BlockedOnStep *BlockedOnStep `json:"blockedOnStep,omitempty"`
	// If the value is false, it means the operation is still in progress. If true, the operation is completed, and either error or response is available.
	Done bool `json:"done,omitempty"`
	// Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time.
	Metadata any `json:"metadata,omitempty"`
	// server-assigned name, which is only unique within the same service that originally returns it.
	Name   string `json:"name,omitempty"`
	Result any    `json:"result,omitempty"`
}

type BlockedOnStep struct {
	Name   string `json:"name,omitempty"`
	Schema string `json:"schema,omitempty"`
}

type Role string

const (
	RoleSystem Role = "system"
	RoleUser   Role = "user"
	RoleModel  Role = "model"
	RoleTool   Role = "tool"
)

type ToolDefinition struct {
	// Valid JSON Schema representing the input of the tool.
	InputSchema map[string]any `json:"inputSchema,omitempty"`
	Name        string         `json:"name,omitempty"`
	// Valid JSON Schema describing the output of the tool.
	OutputSchema map[string]any `json:"outputSchema,omitempty"`
}

type ToolRequestPart struct {
	ToolRequest *ToolRequestPart_toolRequest `json:"toolRequest,omitempty"`
}

type ToolRequestPart_toolRequest struct {
	Input any    `json:"input,omitempty"`
	Name  string `json:"name,omitempty"`
	Ref   string `json:"ref,omitempty"`
}

type ToolResponsePart struct {
	ToolResponse *ToolResponsePart_toolResponse `json:"toolResponse,omitempty"`
}

type ToolResponsePart_toolResponse struct {
	Name   string `json:"name,omitempty"`
	Output any    `json:"output,omitempty"`
	Ref    string `json:"ref,omitempty"`
}
