name: Build CLI Binaries

on:
  push:
    branches:
      - '@invertase/cli-binary'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: macos-latest
            target: darwin-x64
          - os: macos-13
            target: darwin-x64-intel
          - os: windows-latest
            target: win32-x64
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install root dependencies
        run: pnpm i
      
      - name: Install genkit-tools dependencies
        run: pnpm pnpm-install-genkit-tools
      
      - name: Build genkit-tools
        run: pnpm build:genkit-tools
      
      - name: Set binary extension
        id: binary
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == win32-* ]]; then
            echo "ext=.exe" >> $GITHUB_OUTPUT
          else
            echo "ext=" >> $GITHUB_OUTPUT
          fi
      
      - name: Compile CLI binary
        run: |
          cd genkit-tools/cli
          pnpm compile:bun
          mv dist/bin/genkit dist/bin/genkit-${{ matrix.target }}${{ steps.binary.outputs.ext }}
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: genkit-${{ matrix.target }}
          path: genkit-tools/cli/dist/bin/genkit-${{ matrix.target }}${{ steps.binary.outputs.ext }}
          retention-days: 1