# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Bump and Tag CLI Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major
          - prerelease
          - premajor
          - preminor
          - prepatch
      preid:
        description: Prerelease identifier
        type: string
        default: rc
        required: true

jobs:
  build:
    name: Version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v3
      - name: Set up node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: 'genkit-tools/common version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: genkit-tools/common
        with:
          default: ${{ inputs.releaseType }}
          version-type: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/tools-common version to {{version}}'
          tag-prefix:  '@genkit-ai/tools-common@'
      - name: 'genkit-tools/cli version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: genkit-tools/cli
        with:
          default: ${{ inputs.releaseType }}
          version-type: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump genkit-cli version to {{version}}'
          tag-prefix:  'genkit-cli@'
      - name: 'genkit-tools/telemetry-server version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: genkit-tools/telemetry-server
        with:
          default: ${{ inputs.releaseType }}
          version-type: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/telemetry-server version to {{version}}'
          tag-prefix:  '@genkit-ai/telemetry-server@'
