# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Bump Version for a package

on:
  workflow_dispatch:
    inputs:
      packageDir:
        description: Package dir (ex. js/foo)
        type: string
        required: true
      packageName:
        description: Package name (ex. @genkit-ai/foo)
        type: string
        required: true
      releaseType:
        description: Release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major
          - prerelease
          - premajor
          - preminor
          - prepatch
      preid:
        description: Prerelease identifier
        type: string
        default: rc
        required: true

jobs:
  build:
    name: Version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v3
      - name: Set up node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: 'version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: ${{ inputs.packageDir }}
        with:
          default: ${{ inputs.releaseType }}
          version-type: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump ${{ inputs.packageName }} version to {{version}}'
          tag-prefix:  '${{ inputs.packageName }}@'
