# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Run e2e tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run e2e tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '21', '22']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
      - name: Set up node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run build script
        run: pnpm build
      - name: Run pack:all script
        run: pnpm pack:all
      - name: Install local Genkit
        run: pnpm link ./js/genkit
      - name: Run js tests
        run: pnpm test:js
      - name: Run e2e tests
        run: pnpm test:e2e
      - name: Validate working directory is clean
        run: .github/workflows/scripts/ensure-clean-working-tree.sh
