# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Eng Documentation Checks

on:
  pull_request:
    paths:
      - "py/docs/**"
      - ".github/workflows/engdoc.yml"


jobs:
  engdoc-checks:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ github.workspace }}/go/bin:${{ github.workspace }}/.cargo/bin:${{ github.workspace }}/.local/share/pnpm:${{ github.workspace }}/.local/bin:/usr/local/bin:/usr/bin:/bin
    strategy:
      matrix:
        python-version:
          - "3.12"
      fail-fast: false

    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev cmake curl ripgrep

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: stable

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          cd py
          uv pip install -e .[dev,test,docs]

      - name: Install D2 diagramming tool
        run: |
          go install oss.terrastruct.com/d2@latest

      - name: Install mkdocs
        run: |
          uv tool install \
          mkdocs \
          --with mkdocs-autorefs \
          --with mkdocs-d2-plugin \
          --with mkdocs-literate-nav \
          --with mkdocs-material \
          --with mkdocs-mermaid2-plugin \
          --with mkdocs-minify-plugin \
          --with mkdocstrings[python]

      - name: Build documentation
        run: uv run --directory py mkdocs build
