# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Run Tests

on: pull_request

env:
  GITHUB_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}

jobs:
  build:
    name: Run Tests (just DevUI tests for now)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '21', '22']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
      - name: Set up node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies and build
        run: pnpm build:genkit-tools
      - name: Run tests
        run: pnpm test:genkit-tools
